# Generated by Django 5.1.2 on 2024-11-13 06:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_list', models.CharField(choices=[('Viaje', 'Viaje'), ('Pago deudas', 'Pago deudas'), ('Enganche', 'Enganche'), ('Compra', 'Compra'), ('Otro', 'Otro')], max_length=15)),
                ('saving_date', models.DateField(default=datetime.date.today)),
                ('saving_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saving_concept', models.TextField(max_length=50)),
                ('status_delete', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
            ],
        ),
    ]
