# Generated by Django 4.0.3 on 2022-08-08 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('Ahorro', 'Ahorro'), ('Nómina', 'Nómina'), ('Efectivo', 'Efectivo'), ('Crédito', 'Crédito'), ('Wallet', 'Wallet'), ('Departamental', 'Departamental'), ('Vales', 'Vales')], max_length=15)),
                ('account_number', models.CharField(max_length=128)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('status_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
