# Generated by Django 4.0.3 on 2022-08-08 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_concept', models.TextField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal_period', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual')], max_length=20)),
                ('goal_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal_color', models.CharField(choices=[('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Naranja', 'Naranja'), ('Morado', 'Morado'), ('Rosa', 'Rosa')], max_length=8)),
                ('status_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
