# Generated by Django 4.0.3 on 2022-08-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
                ('label_type', models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=12)),
                ('label_class', models.CharField(choices=[('Fijo', 'Fijo'), ('Variable', 'Variable')], max_length=10)),
                ('label_color', models.CharField(choices=[('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Naranja', 'Naranja'), ('Morado', 'Morado'), ('Rosa', 'Rosa')], max_length=8)),
                ('label_description', models.TextField(max_length=100)),
                ('status_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
